### ISSUE TITLE
Control Company not appearing on the second game

### ISSUE THREAD

**Issue by W1kipedia** [ControlCompany/ControlCompany#183]
**Describe the bug**
When I play with my others friends, after the first game the mod doesn't work anymore. I don't have a menu and I can't control anything, but it does work perfectly fine on the first game we play.

**To Reproduce**
1. Play you're first game as intended
2. Escape the moon, either from death or from pulling the lever
3. Get sent to another moon or the company
4. Menu doesn't appear and can't control monsters as intended on the first game

**Expected behavior**
The mod should work on as many moons as me and my team travel to as I am the host and I'm not hiding the menu with the "u" key

**Screenshots**
__What it looks like the on the first game__
![before](https://github.com/ControlCompany/ControlCompany/assets/13318752/58322011-8239-4739-9bb9-b5ecc948a1aa)
__What it looks like on the second game__
![after](https://github.com/ControlCompany/ControlCompany/assets/13318752/c9bdbeae-467a-4a89-8aa9-9c824b75b349)

**Mod version (please complete the following information):**
You can find the version of the mod in the Thunderstore mod manager.
Latest version: v1.1.6

**Additional context**
If useful, this is the mods we installed together: 018dc8df-bd49-cdfa-6f6d-f5252bd60cda

**Comment by klampzlamps** [comment]
Is it a specific moon? Can you try with only the mod enabled and no other mods? 

Do you need to go to the company building first and then another moon? Was the quota changed?

**Comment by klampzlamps** [comment]
If you have the bepinex terminal window opened in the side, a screenshot of that when you change moons would help as well

**Comment by W1kipedia** [comment]
I'll do it without the other mods in a few but here's the screenshots of the terminal, the first one screenshot is the first game and the second one is the game directly after that one
![image](https://github.com/ControlCompany/ControlCompany/assets/13318752/06716c41-1960-41dc-a18a-956cd0549163)
![image](https://github.com/ControlCompany/ControlCompany/assets/13318752/40ada09a-1326-41c8-a117-0b3cc8276077)
I think that's all the logs that came out of ControlCompany in the terminal but it was moving pretty fast to screenshot.

To answer your questions:
1. It's to any of the moons, even modded ones, and the company too. So basically level switching in general and the mod would just not appear to work at all. So basically the first game will work at intended, and then **every** round/company visit after that, it will not work. (even when the quota changes)

**Comment by W1kipedia** [comment]
Oddly enough, the mod works just fine on its own without the other ones instead. But I'm so confused on what might be conflicting it? None of the mods I'm using are really changing around entities other than the skinwalker mod I suppose. Is there any mods known to cause issues with ControlCompany?

**Comment by klampzlamps** [comment]
Can you send the list of mods? There might be one that adds a level/map to the pool. From your screenshots of the terminal it looks like it crashes when it tries to read all the map data to load the full list of enemies.

**Comment by W1kipedia** [comment]
I added the modlist code in the original comment "018dc8df-bd49-cdfa-6f6d-f5252bd60cda" but here's the text version list of all the mods 
```
BepInEx-BepInExPack-5.4.2100
notnotnotswipez-MoreCompany-1.8.1
anormaltwig-LateCompany-1.0.11
x753-More_Suits-1.4.1
ButteryStancakes-AccurateStaminaDisplay-2.0.1
RickArg-Helmet_Cameras-2.1.5
tinyhoot-ShipLoot-1.0.0
Blorb-WeatherMultipliers-1.1.0
DanteStern-DanteCosmetics-1.1.0
FlipMods-ReservedItemSlotCore-1.8.17
RogueCodes-ReservedKeySlot-1.0.4
matsuura-HealthMetrics-1.0.2
saint_kendrick-Lethal_Doors-1.0.4
Drakorle-MoreItems-1.0.2
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.2
Pinta-PintoBoy-1.0.4
AinaVT-YippeeScrap-1.0.7
Kittenji-Maxwell_ScrapItem-1.0.1
bigmcnugget-VanillaContentExpansion-0.1.8
Pooble-LCBetterSaves-1.7.3
SirTyler-BetterTeleporter-1.2.2
Hardy-LCMaxSoundsFix-1.1.0
MoonJuice-RubberChicken-1.0.3
FutureSavior-Hold_Scan_Button-1.1.1
Aelstraz-BetterSpectator-1.1.0
EliteMasterEric-Coroner-1.6.0
Hamunii-JetpackWarning-2.2.0
Hamunii-JetpackFallFix-2.0.1
Hamunii-JetpacksCarryBigItems-1.0.2
Rune580-LethalCompany_InputUtils-0.6.3
NotAtomicBomb-TerminalApi-1.5.2
red_eye-LethalAutocomplete-0.4.3
linkoid-DissonanceLagFix-1.0.0
RugbugRedfern-Skinwalkers-4.0.1
Coppertiel-MaskedEnemyOverhaulFork-3.1.990
Sligili-HDLethalCompany-1.5.6
ControlCompany-ControlCompany-1.1.6
```

**Comment by klampzlamps** [comment]
Difficult to isolate which mod, but I've make changes in the next update that will check for any failures/issues in loading the list of monsters. Hopefully will resolve this issue.

**Comment by klampzlamps** [comment]
I've just released an update that hopefully resolves this issue, please download the latest version (v1.1.8)

**Comment by W1kipedia** [comment]
Unfortunately it didn't seem to fix my issue (with all the other mods installed). Here's a screenshot of the terminal window
![image](https://github.com/ControlCompany/ControlCompany/assets/13318752/a4bb6fb7-dcf4-43bb-a85a-d1ac50e46f2e)

I might just only use the mod itself without the other mods installed because it does seem to work fine on its own. But it's odd that I can't figure out what mod it is

**Comment by klampzlamps** [comment]
Looking at that terminal it now seems like it’s a different error. That error is not related to ControlCompany, but it does identify what the issue is.

My high level hypothesis is that one of the mods is adding a new enemy but is not configured properly. The base game expects all enemies have an “enemyType” but it looks like one of the mods is not configuring that value for a new enemy.

**Comment by klampzlamps** [comment]
Glad it helped :D

**Comment by W1kipedia** [comment]
One thing to note, I just tried it and the base mod for the masked ([located here](https://thunderstore.io/c/lethal-company/p/HomelessGinger/MaskedEnemyOverhaul/)) DOES work. But the fork does not work. I'm assuming the person who forked it might've also messed up the way to setup the enemies, who knows
